[build]
target = "static/index.html"
dist = "dist"
public_url = "/wakalog/"

[watch]
path = ["src", "static"]
ignore = []

[clean]
dist = "dist"
cargo = false

[[proxy]]
backend = "http://localhost:5005/wakalog/api/"